[package]
name = "tree-sitter-qwen-chatml"
description = "Parser for raw prompts and completions when working with Qwen models."
version = "0.1.0"
authors = ["Wes Higbee"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "qwen-chatml"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "https://github.com/g0t4/tree-sitter-qwen_chatml"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "/LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.26.0"
